language: objective-c
before_install:
  - brew update
install:
  - echo $PWD
  - ls $PWD
  - mkdir -p $(brew --repo)/Library/Taps/WorthGodwin
  - ln -s $PWD $(brew --repo)/Library/Taps/WorthGodwin/bitseeds
  - brew tap --repair

script:
- brew install bitseeds --HEAD --with-cli